
services:
  postgres:
    image: postgres:16
    container_name: postgres_coins
    environment:
      POSTGRES_USER: andy
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: